### ISSUE TITLE
UI Bug - Some labels overflow the label box in the sidebar

### ISSUE THREAD

**Issue by lessej** [tnc-ca-geo/animl-frontend#263] opened 2024-12-11 16:11 UTC
![image](https://github.com/user-attachments/assets/2c375285-75c9-435c-b274-9b2eba1aac9c)

**Context**
In the preview menu for images, some of the labels will overflow their box and cover the next image preview box instead of being hidden.  This doesn't happen for all labels so some investigation is needed to determine what styles are causing the issue.

**Reproduction Steps**
Repeatedly add a label to an object or multiple objects in an image until there is enough that the labels wrap to a new line and overflow their bounding box.

**Comment by nathanielrindlaub** [comment] 2024-12-18 23:20
Thanks @lessej. Closing this out as it's a duplicate of #186

**Closed by nathanielrindlaub** 2024-12-18 23:20 UTC
Labels: bug, UX, UI
